SITE_CODE_MAPPING = {
    "1": "3",
    "Hospital e Maternidade Dr. Christóvão da Gama S.A": "3",
    "2": "4",
    "Irmandade da Santa Casa de Misericórdia de Santos": "4",
    "3": "5",
    "Maternidade e Cirurgia Nossa Senhora do Rocio S.A.": "5",
    "4": "56",
    "Unimed de Brusque Cooperativa de Trabalho Médico": "56",
    "5": "59",
    "Centro de Investigação Clínica Ciências Médicas (CIC CMMG)": "59",
    "6": "60",
    "Vidamed Care Clínica E Residência Assistida S/A": "60",
    "7": "69",
    "Instituto ATENA": "69",
    "8": "57",
    "Unimed Fortaleza": "57",
    "9": "63",
    "Hospital Estadual Dr. Jayme Santos Neves (Secretaria de Estado da Saúde)": "63",
    "10": "68",
    "Centro de Oncologia do Paraná": "68",
    "11": "70",
    "InovaEduk - Indacor": "70",
}