SITE_CODE_MAPPING = {
    "1": "3",
    "Hospital e Maternidade Dr. Christóvão da Gama S.A": "3",
    "2": "4",
    "Irmandade da Santa Casa de Misericórdia de Santos": "4",
    "3": "76",
    "Clinica de Ortopedia Campo Largo S/S LTDA": "76",
    "4": "56",
    "Unimed de Brusque Cooperativa de Trabalho Médico": "56",
    "5": "59",
    "Centro de Investigação Clínica Ciências Médicas (CIC CMMG)": "59",
    "6": "74",
    "Núcleo de Pesquisa Clínica em Ortopedia Regenerativa": "74",
    "7": "36",
    "HELP Paraíba": "36",
    "8": "57",
    "Unimed Fortaleza": "57",
    "9": "78",
    "Santa Marcelina": "78",
    "10": "68",
    "Centro de Oncologia do Paraná": "68",
    "11": "70",
    "InovaEduk - Indacor": "70",
}